In [1]:
# Write dependencies here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import argparse
import re
import glob
import subprocess

In [2]:
# Read the CSV file
df = pd.read_csv('data/Eber-insights-cig.csv')

# Display the dataframe with all columns
pd.set_option('display.max_columns', None)
print(df.head())

    Member Id          Name                    Email  Birth month  Birth year  \
0  12353112.0        Haairy   hairyazahar7@gmail.com          1.0      2002.0
1  12353059.0  Avelene wong     avelene920@gmail.com          9.0      2001.0
2  12353005.0         David  davidquan2001@gmail.com          2.0      2003.0
3  12352986.0       Malcolm    malcolmyong@yahoo.com         12.0      1976.0
4  12352984.0          Ynez       ynezliew@gmail.com          9.0      2001.0

   Birth day         Phone Phone Code  External Member Id  Company Name  \
0       24.0  6.011280e+11         MY                 NaN           NaN
1       20.0  6.017230e+10         MY                 NaN           NaN
2       24.0  6.016291e+10         MY                 NaN           NaN
3       21.0  6.011120e+11         MY                 NaN           NaN
4       24.0  6.018781e+10         MY                 NaN           NaN

  Store Staff Member Since Enrolled At Sign up at  Number of Visit Last Visit  \
0         NaN    24-Dec-23   24-Dec-23        NaN              0.0        NaN
1         NaN    24-Dec-23   24-Dec-23        NaN              0.0        NaN
2         NaN    24-Dec-23   24-Dec-23        NaN              0.0        NaN
3         NaN    24-Dec-23   24-Dec-23        NaN              0.0        NaN
4         NaN    24-Dec-23   24-Dec-23        NaN              0.0        NaN

  Member Tier  Member Tier Id  Status  Expire Date  Points Earned  \
0       Basic         12898.0  Active          NaN            0.0
1       Basic         12898.0  Active          NaN            0.0
2       Basic         12898.0  Active          NaN            0.0
3       Basic         12898.0  Active          NaN            7.0
4       Basic         12898.0  Active          NaN            0.0

   Points Balance  Total Spending Currency  Claimed Rewards  \
0             0.0             0.0      MYR              0.0
1             0.0             0.0      MYR              0.0
2             0.0             0.0      MYR              0.0
3             7.0             0.0      MYR              0.0
4             0.0             0.0      MYR              0.0

   Member Card Serial Number  Utm Source  Utm Medium  Utm Campaign  Block  \
0                        NaN         NaN         NaN           NaN    NaN
1                        NaN         NaN         NaN           NaN    NaN
2                        NaN         NaN         NaN           NaN    NaN
3                        NaN         NaN         NaN           NaN    NaN
4                        NaN         NaN         NaN           NaN    NaN

   Floor  Unit  Master Member Id  Master Member Name Category  \
0    NaN   NaN               NaN                 NaN      New
1    NaN   NaN               NaN                 NaN      New
2    NaN   NaN               NaN                 NaN      New
3    NaN   NaN               NaN                 NaN    Loyal
4    NaN   NaN               NaN                 NaN      New

  Sms Transactions Subscription Email Transactions Subscription  \
0                           Yes                             Yes
1                           Yes                             Yes
2                           Yes                             Yes
3                           Yes                             Yes
4                           Yes                             Yes

  Sms Marketing Subscription Email Marketing Subscription  \
0                        Yes                          Yes
1                        Yes                          Yes
2                        Yes                          Yes
3                        Yes                          Yes
4                        Yes                          Yes

   Points Will Expire in 7 Days  Points Will Expire in 14 Days  \
0                           0.0                            0.0
1                           0.0                            0.0
2                           0.0                            0.0
3                           0.0                            0.0
4                           0.0                            0.0

   Points Will Expire in 30 Days  Points Will Expire in 60 Days  \
0                            0.0                            0.0
1                            0.0                            0.0
2                            0.0                            0.0
3                            0.0                            0.0
4                            0.0                            0.0

   Points Will Expire in 90 Days  Points Will Expire in 1 Month  \
0                            0.0                            0.0
1                            0.0                            0.0
2                            0.0                            0.0
3                            0.0                            0.0
4                            0.0                            0.0

   Points Will Expire in 2 Months  Points Will Expire in 3 Months
0                             0.0                             0.0
1                             0.0                             0.0
2                             0.0                             0.0
3                             0.0                             0.0
4                             0.0                             0.0

In [3]:
# Check for columns with only NaN in the dataframe and store them in a list
nan_columns = df.columns[df.isnull().all()].tolist()

# Display nan_columns
print(nan_columns)

# Display the updated dataframe
df

['External Member Id', 'Company Name', 'Expire Date', 'Member Card Serial Number', 'Utm Source', 'Utm Medium', 'Utm Campaign', 'Block', 'Floor', 'Unit', 'Master Member Id', 'Master Member Name']

,Member Id,Name,Email,Birth month,Birth year,Birth day,Phone,Phone Code,External Member Id,Company Name,Store Staff,Member Since,Enrolled At,Sign up at,Number of Visit,Last Visit,Member Tier,Member Tier Id,Status,Expire Date,Points Earned,Points Balance,Total Spending,Currency,Claimed Rewards,Member Card Serial Number,Utm Source,Utm Medium,Utm Campaign,Block,Floor,Unit,Master Member Id,Master Member Name,Category,Sms Transactions Subscription,Email Transactions Subscription,Sms Marketing Subscription,Email Marketing Subscription,Points Will Expire in 7 Days,Points Will Expire in 14 Days,Points Will Expire in 30 Days,Points Will Expire in 60 Days,Points Will Expire in 90 Days,Points Will Expire in 1 Month,Points Will Expire in 2 Months,Points Will Expire in 3 Months
0,12353112.0,Haairy,hairyazahar7@gmail.com,1.0,2002.0,24.0,6.011280e+11,MY,NaN,NaN,NaN,24-Dec-23,24-Dec-23,NaN,0.0,NaN,Basic,12898.0,Active,NaN,0.0,0.0,0.0,MYR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,12353059.0,Avelene wong,avelene920@gmail.com,9.0,2001.0,20.0,6.017230e+10,MY,NaN,NaN,NaN,24-Dec-23,24-Dec-23,NaN,0.0,NaN,Basic,12898.0,Active,NaN,0.0,0.0,0.0,MYR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12353005.0,David,davidquan2001@gmail.com,2.0,2003.0,24.0,6.016291e+10,MY,NaN,NaN,NaN,24-Dec-23,24-Dec-23,NaN,0.0,NaN,Basic,12898.0,Active,NaN,0.0,0.0,0.0,MYR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,12352986.0,Malcolm,malcolmyong@yahoo.com,12.0,1976.0,21.0,6.011120e+11,MY,NaN,NaN,NaN,24-Dec-23,24-Dec-23,NaN,0.0,NaN,Basic,12898.0,Active,NaN,7.0,7.0,0.0,MYR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12352984.0,Ynez,ynezliew@gmail.com,9.0,2001.0,24.0,6.018781e+10,MY,NaN,NaN,NaN,24-Dec-23,24-Dec-23,NaN,0.0,NaN,Basic,12898.0,Active,NaN,0.0,0.0,0.0,MYR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,12284635.0,Kimm Cheng,c.wankimm@gmail.com,4.0,1990.0,26.0,6.012239e+10,MY,NaN,NaN,NaN,20-Dec-23,20-Dec-23,NaN,0.0,NaN,Basic,12898.0,Active,NaN,7.0,7.0,0.0,MYR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
514,12284434.0,Kimi,kimi.lee.meow@gmail.com,12.0,1989.0,28.0,6.012275e+10,MY,NaN,NaN,NaN,20-Dec-23,20-Dec-23,NaN,2.0,24/12/23 16:37,Basic,12898.0,Active,NaN,110.0,70.0,79.0,MYR,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
515,12274702.0,NaN,NaN,NaN,NaN,NaN,6.012532e+10,MY,NaN,NaN,NaN,19-Dec-23,19-Dec-23,Tug Gelato,0.0,NaN,Basic,12898.0,Active,NaN,0.0,0.0,0.0,MYR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
516,NaN,NaN,NaN,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Output non-NaN values for all columns in `nan_columns`
for col in nan_columns:
    print(df[col].unique())
# df['Store Staff'].unique()

[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]
[nan]

In [5]:
# Drop NaN columns if necessary
if nan_columns:
    df = df.drop(nan_columns, axis=1)

print(df.head())

    Member Id          Name                    Email  Birth month  Birth year  \
0  12353112.0        Haairy   hairyazahar7@gmail.com          1.0      2002.0
1  12353059.0  Avelene wong     avelene920@gmail.com          9.0      2001.0
2  12353005.0         David  davidquan2001@gmail.com          2.0      2003.0
3  12352986.0       Malcolm    malcolmyong@yahoo.com         12.0      1976.0
4  12352984.0          Ynez       ynezliew@gmail.com          9.0      2001.0

   Birth day         Phone Phone Code Store Staff Member Since Enrolled At  \
0       24.0  6.011280e+11         MY         NaN    24-Dec-23   24-Dec-23
1       20.0  6.017230e+10         MY         NaN    24-Dec-23   24-Dec-23
2       24.0  6.016291e+10         MY         NaN    24-Dec-23   24-Dec-23
3       21.0  6.011120e+11         MY         NaN    24-Dec-23   24-Dec-23
4       24.0  6.018781e+10         MY         NaN    24-Dec-23   24-Dec-23

  Sign up at  Number of Visit Last Visit Member Tier  Member Tier Id  Status  \
0        NaN              0.0        NaN       Basic         12898.0  Active
1        NaN              0.0        NaN       Basic         12898.0  Active
2        NaN              0.0        NaN       Basic         12898.0  Active
3        NaN              0.0        NaN       Basic         12898.0  Active
4        NaN              0.0        NaN       Basic         12898.0  Active

   Points Earned  Points Balance  Total Spending Currency  Claimed Rewards  \
0            0.0             0.0             0.0      MYR              0.0
1            0.0             0.0             0.0      MYR              0.0
2            0.0             0.0             0.0      MYR              0.0
3            7.0             7.0             0.0      MYR              0.0
4            0.0             0.0             0.0      MYR              0.0

  Category Sms Transactions Subscription Email Transactions Subscription  \
0      New                           Yes                             Yes
1      New                           Yes                             Yes
2      New                           Yes                             Yes
3    Loyal                           Yes                             Yes
4      New                           Yes                             Yes

  Sms Marketing Subscription Email Marketing Subscription  \
0                        Yes                          Yes
1                        Yes                          Yes
2                        Yes                          Yes
3                        Yes                          Yes
4                        Yes                          Yes

   Points Will Expire in 7 Days  Points Will Expire in 14 Days  \
0                           0.0                            0.0
1                           0.0                            0.0
2                           0.0                            0.0
3                           0.0                            0.0
4                           0.0                            0.0

   Points Will Expire in 30 Days  Points Will Expire in 60 Days  \
0                            0.0                            0.0
1                            0.0                            0.0
2                            0.0                            0.0
3                            0.0                            0.0
4                            0.0                            0.0

   Points Will Expire in 90 Days  Points Will Expire in 1 Month  \
0                            0.0                            0.0
1                            0.0                            0.0
2                            0.0                            0.0
3                            0.0                            0.0
4                            0.0                            0.0

   Points Will Expire in 2 Months  Points Will Expire in 3 Months
0                             0.0                             0.0
1                             0.0                             0.0
2                             0.0                             0.0
3                             0.0                             0.0
4                             0.0                             0.0

In [6]:
# Print the number of rows that is NaN in the `Member Id` column
print(f"Number of rows that is NaN in the `Member Id` column:", df['Member Id'].isnull().sum())

# Drop the nan values in the `Member Id` column
df = df.dropna(subset=['Member Id'])

# Print the number of rows that is NaN in the `Name` column with description for the print statement
print(f"Number of rows that is NaN in the `Name` column:", df['Name'].isnull().sum())

# Drop the nan values in the `Name` column
df = df.dropna(subset=['Name'])

Number of rows that is NaN in the `Member Id` column: 3
Number of rows that is NaN in the `Name` column: 1

In [7]:
# Check for columns with NaN values
nan_columns = df.columns[df.isnull().any()].tolist()

# Display unique values for columns with NaN values
for col in nan_columns:
    unique_values = df[col].unique()
    print(f"Column: {col}, Unique Values: {unique_values}")

Column: Store Staff, Unique Values: [nan 'Dylan' 'Scoopy1' 'August']
Column: Sign up at, Unique Values: [nan 'Tug Gelato']
Column: Last Visit, Unique Values: [nan '24/12/23 14:03' '24/12/23 14:11' '24/12/23 12:38' '23/12/23 21:55'
 '23/12/23 18:55' '23/12/23 18:38' '23/12/23 20:18' '23/12/23 18:05'
 '23/12/23 18:01' '23/12/23 17:59' '23/12/23 17:01' '23/12/23 16:52'
 '23/12/23 17:15' '23/12/23 14:21' '23/12/23 15:19' '23/12/23 13:35'
 '23/12/23 12:12' '23/12/23 12:23' '23/12/23 20:34' '23/12/23 12:06'
 '23/12/23 12:20' '23/12/23 10:58' '23/12/23 11:05' '23/12/23 10:51'
 '23/12/23 10:33' '23/12/23 10:32' '23/12/23 10:22' '22/12/23 21:03'
 '22/12/23 21:10' '22/12/23 20:29' '22/12/23 20:05' '22/12/23 20:03'
 '22/12/23 20:00' '22/12/23 18:47' '23/12/23 13:02' '24/12/23 16:37']

In [8]:
df['Store Staff'] = df['Store Staff'].fillna('Admin')
df['Sign up at'] = df['Sign up at'].fillna('Tug Gelato')

In [9]:
# Print nan rows for `Last Visit`
print(df[df['Last Visit'].isnull()])

# Fill NaN values in `Last Visit` with `Member Since` values
df['Last Visit'] = df['Last Visit'].fillna(df['Member Since'])

# Check for nan values
nan_columns = df.columns[df.isnull().any()].tolist()
print(nan_columns)

      Member Id                   Name                      Email  \
0    12353112.0                 Haairy     hairyazahar7@gmail.com
1    12353059.0           Avelene wong       avelene920@gmail.com
2    12353005.0                  David    davidquan2001@gmail.com
3    12352986.0                Malcolm      malcolmyong@yahoo.com
4    12352984.0                   Ynez         ynezliew@gmail.com
..          ...                    ...                        ...
509  12308935.0                  Lyn h       lynetharun@gmail.com
510  12303329.0  Afrina Asma’ Alhannah     afrinaasma18@gmail.com
511  12303182.0           Azhana Azhan  alhumairaazhana@gmail.com
512  12303101.0                 Xin Yi       wxinyi0426@gmail.com
513  12284635.0             Kimm Cheng        c.wankimm@gmail.com

     Birth month  Birth year  Birth day         Phone Phone Code Store Staff  \
0            1.0      2002.0       24.0  6.011280e+11         MY       Admin
1            9.0      2001.0       20.0  6.017230e+10         MY       Admin
2            2.0      2003.0       24.0  6.016291e+10         MY       Admin
3           12.0      1976.0       21.0  6.011120e+11         MY       Admin
4            9.0      2001.0       24.0  6.018781e+10         MY       Admin
..           ...         ...        ...           ...        ...         ...
509         12.0      1982.0        4.0  6.012316e+10         MY       Admin
510          3.0      2004.0       18.0  6.013381e+10         MY       Admin
511         10.0      2000.0        6.0  6.019374e+10         MY       Admin
512          4.0      2002.0       26.0  6.011190e+11         MY       Admin
513          4.0      1990.0       26.0  6.012239e+10         MY       Admin

    Member Since Enrolled At  Sign up at  Number of Visit Last Visit  \
0      24-Dec-23   24-Dec-23  Tug Gelato              0.0        NaN
1      24-Dec-23   24-Dec-23  Tug Gelato              0.0        NaN
2      24-Dec-23   24-Dec-23  Tug Gelato              0.0        NaN
3      24-Dec-23   24-Dec-23  Tug Gelato              0.0        NaN
4      24-Dec-23   24-Dec-23  Tug Gelato              0.0        NaN
..           ...         ...         ...              ...        ...
509    21-Dec-23   21-Dec-23  Tug Gelato              0.0        NaN
510    21-Dec-23   21-Dec-23  Tug Gelato              0.0        NaN
511    21-Dec-23   21-Dec-23  Tug Gelato              0.0        NaN
512    21-Dec-23   21-Dec-23  Tug Gelato              0.0        NaN
513    20-Dec-23   20-Dec-23  Tug Gelato              0.0        NaN

    Member Tier  Member Tier Id  Status  Points Earned  Points Balance  \
0         Basic         12898.0  Active            0.0             0.0
1         Basic         12898.0  Active            0.0             0.0
2         Basic         12898.0  Active            0.0             0.0
3         Basic         12898.0  Active            7.0             7.0
4         Basic         12898.0  Active            0.0             0.0
..          ...             ...     ...            ...             ...
509       Basic         12898.0  Active           10.0             0.0
510       Basic         12898.0  Active           35.0             5.0
511       Basic         12898.0  Active           32.0             2.0
512       Basic         12898.0  Active           30.0             0.0
513       Basic         12898.0  Active            7.0             7.0

     Total Spending Currency  Claimed Rewards Category  \
0               0.0      MYR              0.0      New
1               0.0      MYR              0.0      New
2               0.0      MYR              0.0      New
3               0.0      MYR              0.0    Loyal
4               0.0      MYR              0.0      New
..              ...      ...              ...      ...
509             0.0      MYR              1.0    Loyal
510             0.0      MYR              3.0    Loyal
511             0.0      MYR              3.0    Loyal
512             0.0      MYR              3.0    Loyal
513             0.0      MYR              0.0    Loyal

    Sms Transactions Subscription Email Transactions Subscription  \
0                             Yes                             Yes
1                             Yes                             Yes
2                             Yes                             Yes
3                             Yes                             Yes
4                             Yes                             Yes
..                            ...                             ...
509                           Yes                             Yes
510                           Yes                             Yes
511                           Yes                             Yes
512                           Yes                             Yes
513                           Yes                             Yes

    Sms Marketing Subscription Email Marketing Subscription  \
0                          Yes                          Yes
1                          Yes                          Yes
2                          Yes                          Yes
3                          Yes                          Yes
4                          Yes                          Yes
..                         ...                          ...
509                        Yes                          Yes
510                        Yes                          Yes
511                        Yes                          Yes
512                        Yes                          Yes
513                        Yes                          Yes

     Points Will Expire in 7 Days  Points Will Expire in 14 Days  \
0                             0.0                            0.0
1                             0.0                            0.0
2                             0.0                            0.0
3                             0.0                            0.0
4                             0.0                            0.0
..                            ...                            ...
509                           0.0                            0.0
510                           0.0                            0.0
511                           0.0                            0.0
512                           0.0                            0.0
513                           0.0                            0.0

     Points Will Expire in 30 Days  Points Will Expire in 60 Days  \
0                              0.0                            0.0
1                              0.0                            0.0
2                              0.0                            0.0
3                              0.0                            0.0
4                              0.0                            0.0
..                             ...                            ...
509                            0.0                            0.0
510                            0.0                            0.0
511                            0.0                            0.0
512                            0.0                            0.0
513                            0.0                            0.0

     Points Will Expire in 90 Days  Points Will Expire in 1 Month  \
0                              0.0                            0.0
1                              0.0                            0.0
2                              0.0                            0.0
3                              0.0                            0.0
4                              0.0                            0.0
..                             ...                            ...
509                            0.0                            0.0
510                            0.0                            0.0
511                            0.0                            0.0
512                            0.0                            0.0
513                            0.0                            0.0

     Points Will Expire in 2 Months  Points Will Expire in 3 Months
0                               0.0                             0.0
1                               0.0                             0.0
2                               0.0                             0.0
3                               0.0                             0.0
4                               0.0                             0.0
..                              ...                             ...
509                             0.0                             0.0
510                             0.0                             0.0
511                             0.0                             0.0
512                             0.0                             0.0
513                             0.0                             0.0

[477 rows x 35 columns]
[]

In [10]:
# # Drop duplicate rows
# df = df.drop_duplicates()

# # Drop rows with missing values
# df = df.dropna()

# # Convert columns to appropriate data types if needed
# df['Date'] = pd.to_datetime(df['Date'])
# df['Quantity'] = df['Quantity'].astype(int)

# # Perform any additional data cleaning or preprocessing steps as needed

# # Display the cleaned dataframe
# df

# Print the df info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 514 entries, 0 to 514
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Member Id                        514 non-null    float64
 1   Name                             514 non-null    object
 2   Email                            514 non-null    object
 3   Birth month                      514 non-null    float64
 4   Birth year                       514 non-null    float64
 5   Birth day                        514 non-null    float64
 6   Phone                            514 non-null    float64
 7   Phone Code                       514 non-null    object
 8   Store Staff                      514 non-null    object
 9   Member Since                     514 non-null    object
 10  Enrolled At                      514 non-null    object
 11  Sign up at                       514 non-null    object
 12  Number of Visit                  514 non-null    float64
 13  Last Visit                       514 non-null    object
 14  Member Tier                      514 non-null    object
 15  Member Tier Id                   514 non-null    float64
 16  Status                           514 non-null    object
 17  Points Earned                    514 non-null    float64
 18  Points Balance                   514 non-null    float64
 19  Total Spending                   514 non-null    float64
 20  Currency                         514 non-null    object
 21  Claimed Rewards                  514 non-null    float64
 22  Category                         514 non-null    object
 23  Sms Transactions Subscription    514 non-null    object
 24  Email Transactions Subscription  514 non-null    object
 25  Sms Marketing Subscription       514 non-null    object
 26  Email Marketing Subscription     514 non-null    object
 27  Points Will Expire in 7 Days     514 non-null    float64
 28  Points Will Expire in 14 Days    514 non-null    float64
 29  Points Will Expire in 30 Days    514 non-null    float64
 30  Points Will Expire in 60 Days    514 non-null    float64
 31  Points Will Expire in 90 Days    514 non-null    float64
 32  Points Will Expire in 1 Month    514 non-null    float64
 33  Points Will Expire in 2 Months   514 non-null    float64
 34  Points Will Expire in 3 Months   514 non-null    float64
dtypes: float64(19), object(16)
memory usage: 144.6+ KB
None

In [11]:
# Print duplicate rows in the dataframe if any exist
print(df[df.duplicated()])

# Convert "Enrolled At", "Member Since" and "Last Visit" columns to datetime
df['Enrolled At'] = pd.to_datetime(df['Enrolled At'])
df['Member Since'] = pd.to_datetime(df['Member Since'])
df['Last Visit'] = pd.to_datetime(df['Last Visit'])

# Print the df info
print(df.info())

Empty DataFrame
Columns: [Member Id, Name, Email, Birth month, Birth year, Birth day, Phone, Phone Code, Store Staff, Member Since, Enrolled At, Sign up at, Number of Visit, Last Visit, Member Tier, Member Tier Id, Status, Points Earned, Points Balance, Total Spending, Currency, Claimed Rewards, Category, Sms Transactions Subscription, Email Transactions Subscription, Sms Marketing Subscription, Email Marketing Subscription, Points Will Expire in 7 Days, Points Will Expire in 14 Days, Points Will Expire in 30 Days, Points Will Expire in 60 Days, Points Will Expire in 90 Days, Points Will Expire in 1 Month, Points Will Expire in 2 Months, Points Will Expire in 3 Months]
Index: []
<class 'pandas.core.frame.DataFrame'>
Index: 514 entries, 0 to 514
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Member Id                        514 non-null    float64
 1   Name                             514 non-null    object
 2   Email                            514 non-null    object
 3   Birth month                      514 non-null    float64
 4   Birth year                       514 non-null    float64
 5   Birth day                        514 non-null    float64
 6   Phone                            514 non-null    float64
 7   Phone Code                       514 non-null    object
 8   Store Staff                      514 non-null    object
 9   Member Since                     514 non-null    datetime64[ns]
 10  Enrolled At                      514 non-null    datetime64[ns]
 11  Sign up at                       514 non-null    object
 12  Number of Visit                  514 non-null    float64
 13  Last Visit                       514 non-null    datetime64[ns]
 14  Member Tier                      514 non-null    object
 15  Member Tier Id                   514 non-null    float64
 16  Status                           514 non-null    object
 17  Points Earned                    514 non-null    float64
 18  Points Balance                   514 non-null    float64
 19  Total Spending                   514 non-null    float64
 20  Currency                         514 non-null    object
 21  Claimed Rewards                  514 non-null    float64
 22  Category                         514 non-null    object
 23  Sms Transactions Subscription    514 non-null    object
 24  Email Transactions Subscription  514 non-null    object
 25  Sms Marketing Subscription       514 non-null    object
 26  Email Marketing Subscription     514 non-null    object
 27  Points Will Expire in 7 Days     514 non-null    float64
 28  Points Will Expire in 14 Days    514 non-null    float64
 29  Points Will Expire in 30 Days    514 non-null    float64
 30  Points Will Expire in 60 Days    514 non-null    float64
 31  Points Will Expire in 90 Days    514 non-null    float64
 32  Points Will Expire in 1 Month    514 non-null    float64
 33  Points Will Expire in 2 Months   514 non-null    float64
 34  Points Will Expire in 3 Months   514 non-null    float64
dtypes: datetime64[ns](3), float64(19), object(13)
memory usage: 144.6+ KB
None

/tmp/ipykernel_64507/1580812582.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Enrolled At'] = pd.to_datetime(df['Enrolled At'])
/tmp/ipykernel_64507/1580812582.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Member Since'] = pd.to_datetime(df['Member Since'])
/tmp/ipykernel_64507/1580812582.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Last Visit'] = pd.to_datetime(df['Last Visit'])

In [12]:
# Check if `Member Since` and `Enrolled At` are equal
print(df['Member Since'].equals(df['Enrolled At']))

# Drop the `Enrolled At` column
df = df.drop('Enrolled At', axis=1)

True

In [13]:
df

,Member Id,Name,Email,Birth month,Birth year,Birth day,Phone,Phone Code,Store Staff,Member Since,Sign up at,Number of Visit,Last Visit,Member Tier,Member Tier Id,Status,Points Earned,Points Balance,Total Spending,Currency,Claimed Rewards,Category,Sms Transactions Subscription,Email Transactions Subscription,Sms Marketing Subscription,Email Marketing Subscription,Points Will Expire in 7 Days,Points Will Expire in 14 Days,Points Will Expire in 30 Days,Points Will Expire in 60 Days,Points Will Expire in 90 Days,Points Will Expire in 1 Month,Points Will Expire in 2 Months,Points Will Expire in 3 Months
0,12353112.0,Haairy,hairyazahar7@gmail.com,1.0,2002.0,24.0,6.011280e+11,MY,Admin,2023-12-24,Tug Gelato,0.0,2023-12-24 00:00:00,Basic,12898.0,Active,0.0,0.0,0.0,MYR,0.0,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,12353059.0,Avelene wong,avelene920@gmail.com,9.0,2001.0,20.0,6.017230e+10,MY,Admin,2023-12-24,Tug Gelato,0.0,2023-12-24 00:00:00,Basic,12898.0,Active,0.0,0.0,0.0,MYR,0.0,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12353005.0,David,davidquan2001@gmail.com,2.0,2003.0,24.0,6.016291e+10,MY,Admin,2023-12-24,Tug Gelato,0.0,2023-12-24 00:00:00,Basic,12898.0,Active,0.0,0.0,0.0,MYR,0.0,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,12352986.0,Malcolm,malcolmyong@yahoo.com,12.0,1976.0,21.0,6.011120e+11,MY,Admin,2023-12-24,Tug Gelato,0.0,2023-12-24 00:00:00,Basic,12898.0,Active,7.0,7.0,0.0,MYR,0.0,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12352984.0,Ynez,ynezliew@gmail.com,9.0,2001.0,24.0,6.018781e+10,MY,Admin,2023-12-24,Tug Gelato,0.0,2023-12-24 00:00:00,Basic,12898.0,Active,0.0,0.0,0.0,MYR,0.0,New,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,12303329.0,Afrina Asma’ Alhannah,afrinaasma18@gmail.com,3.0,2004.0,18.0,6.013381e+10,MY,Admin,2023-12-21,Tug Gelato,0.0,2023-12-21 00:00:00,Basic,12898.0,Active,35.0,5.0,0.0,MYR,3.0,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
511,12303182.0,Azhana Azhan,alhumairaazhana@gmail.com,10.0,2000.0,6.0,6.019374e+10,MY,Admin,2023-12-21,Tug Gelato,0.0,2023-12-21 00:00:00,Basic,12898.0,Active,32.0,2.0,0.0,MYR,3.0,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
512,12303101.0,Xin Yi,wxinyi0426@gmail.com,4.0,2002.0,26.0,6.011190e+11,MY,Admin,2023-12-21,Tug Gelato,0.0,2023-12-21 00:00:00,Basic,12898.0,Active,30.0,0.0,0.0,MYR,3.0,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
513,12284635.0,Kimm Cheng,c.wankimm@gmail.com,4.0,1990.0,26.0,6.012239e+10,MY,Admin,2023-12-20,Tug Gelato,0.0,2023-12-20 00:00:00,Basic,12898.0,Active,7.0,7.0,0.0,MYR,0.0,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
514,12284434.0,Kimi,kimi.lee.meow@gmail.com,12.0,1989.0,28.0,6.012275e+10,MY,Admin,2023-12-20,Tug Gelato,2.0,2023-12-24 16:37:00,Basic,12898.0,Active,110.0,70.0,79.0,MYR,4.0,Loyal,Yes,Yes,Yes,Yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
# Save the cleaned dataframe to a CSV file without the index column and with the header row included
df.to_csv('data/Eber-insights-cig-cleaned.csv', index=False, header=True)